### ISSUE TITLE
Where is the out put displayed?

### ISSUE THREAD

**Issue by andrewfed403** [carlosefr/magstripelib#1]
like the leds are changing with the insertion of a card and stuff but im getting 0 output in the serial monitor .. im using an osepp nano

**Comment by carlosefr** [comment]
With the example `MagStripeReader.ino` sketch? Does the error LED blink?

If it does, then the card isn't being read properly (no serial output in this case). Otherwise, check if you have the correct rate set in the serial monitor (9600 bps).

**Comment by andrewfed403** [comment]
The orange light is being turned off and remains off upon card insertion
and turns back on when it's removed , is that what you mean ?

**Comment by carlosefr** [comment]
The example sketch uses two LEDs: one to show that a card is being read (ON when swiping a card, OFF otherwise) and another that blinks briefly if the swiped data cannot be decoded (the error LED).

The sketch uses pin 13 for the read LED. I'm assuming your "orange light" is this one. And from that it looks that your reader uses the "card present" (CLS) line to indicate a fully inserted card instead of a card being swiped. This library doesn't support this type of readers.

**Comment by andrewfed403** [comment]
panasonic zu-1870ma6t2 is the reader im using

**Comment by andrewfed403** [comment]
and it uses the cld line

**Comment by carlosefr** [comment]
The datasheet says the CLD line is basically a switch indicating the card is fully inserted. The way the library works internally means this requires some modifications. These shouldn't be too difficult, the tricky part is integrating them with existing behavior.

You're welcome to fork the code and implement the necessary changes.

**Comment by andrewfed403** [comment]
is the source code available ?
